# This is a basic workflow to help you get started with Actions

name: events

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/5 * * * *' 
     
  # Triggers the workflow on push or pull request events but only for the "main" branch
 # push:
   # branches: [ "main" ]
 # pull_request:
  #  branches: [ "main" ]
  #issues:
  #  types: [opened, closed, reopened]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build-type: [debug, release]

    steps:
      - uses: actions/checkout@v4

      - name: Show build type
        run: echo "Running in ${{ matrix.build-type }} mode"
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
