name: Manual Trigger Demo

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo " Hello! This workflow was triggered manually."
